---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  releaseName: ingress-nginx
  persistentClient: false # hopefully this mimics --wait
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      version: 4.10.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  install:
    createNamespace: true
    remediation:
      retries: -1
  interval: 3m0s
  targetNamespace: ingress-nginx
