apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:a1oWNKTmJU+cigfGKeCKjhpHO4uy25M9+iUHjdS8b8lGeFvk9uppb/JzbNYG4q3Jq2Mz0pOXyKRifYSQDZwwsL0Gsjghl1TMsgmC+P+oTiBXgMykay3xwqja3LWnpVcVKBoKkKfkdtc2bbEhK4EwNAmV+AZI2nD7JGU34eB9c+1PpPH9sX+VJ3MxNgdsO0mTE2LvzrSZ5NHUndsiGF5CI4IiHFMcrh6ldVOO3QIPUz2L4cH0HE3Ko86Mk9QBwJkq940es0sBCJwYurAIyuqVpP+TMh42seX0z1zKP/KK5WLJzwzm93rcICcin5N0JM6t1jUC3AZmpDV5ybgz62LH3QKdsLDf4wPGG8DuyDUO8UKmPSz7S7Ow23zFZeqARVZykdWbVgxA9Zu1cbgj4p/0uGK0/rC6MXrFOskmPq3NytAswrAMB+XC4jrwOWPE/fXxa/iOdiZQM6xCmJzmRnc6icwhKi67PwgjO6hkirQZhwNMdILYReupDS4EPNjgG2uJCwKLNOA2MJ6KmxTzFhgXr6wLbdtRBy93CcgWg42xXfDiMeHrFu7wRIpkrRfDaVhGYFVyw3IFGN4LeFbqWZsq1lYDWcse4tSu7mq8ybCs3VfiLOhjuWfqxqWO1ttrWy9/HZgb6Gd56rcIzqnujN+bPAd9srLwGMBAgzmfzedouksP2pTcgQksv2I5Xsb6BAoz+xETDka+vhLwMEgVPqFDvzWGJzNyL1Pxlr2ahSCHPy7ONFm9TaSo1Vybt4j7Jmih6JysgFr2LVEng7dMqN4ThQcfzGsokXr4GBL8iM9ZCGE=,iv:p3R2PZczMqycsoz6WbaaWKC382ZUTsY73D02A+tuP1w=,tag:n9h0ftztMq8MCvccOoEXZg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: external-dns-secret-values
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-23T13:27:48Z"
    mac: ENC[AES256_GCM,data:jL3mG8W2tsaFy0LYoMcc9t2EPzthippO8zUeVMe4A5B/Dv76y5q7oP+yPpxKnMKH8oHQjmQtvCWv07ktoBZJ+0MMnQWOvKzPthlymFJyxrMxPoEhVi02t0s6+rZVzHSg4lBJ4oliMHb00kKN0iEYgjrxdt9CO9wyIflY//FlFnM=,iv:VobWatz1AAxbMPCocvgpN6C/StXq0HtX8vrAJvuRuek=,tag:l9+65aEvz9xX84zV7GUekA==,type:str]
    pgp:
        - created_at: "2024-07-02T11:43:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyBxDD99NeTXAQ//UcC0baru3JeM+hu0aFP6/2wOof7iTz2TiYKzlSvnylvW
            qytqNfnbh30gBPZmVMRxC3G/Uce/zIbWa6fksSMI8T8Q49cr3XQIlCuQLOr9gjQL
            JuoJWGMcJT+n4pZbTIylDUX0ECyF+Tv8iUgXIdFDHo1vyIdRt++ee4hvV02HSLVK
            ZBkdfae6/mxKAIqfrKWvPIJ1O9LncfWnPMO/VFb+lhjDypi8fiO0aSCRo/FZwUIa
            azw6zePG+mv9E3osdVdLbL4FcHeZbbyPu7PJcGnsxDrEKIG5T5vKfTCxxgbxBVnV
            SsDyJ6iM4NBSBEDKtlhB+kVt3G3tGjT7szUeiScfNvF81qodkUvG5B+lMjfHoYU0
            0g9X8Tkck8IGf+g/gafkwDLJLwG+ilg6dVTU6BSnD2Lv6ODRQta7wEwBBd7loGn6
            wU6sZgdSAbVhFId8AgDGYr+TGsr88xAYmTNtFi5IlSh69Syu9VWsx+bLioglfpGh
            VBO6KmjLaSXrPtzI+zjRPJEQsjU0QTWGqRKeerdT90k3cXZEHStfuAdgxEV+zyIf
            e81TYHN8pIVo8qjhtxPtUR0Q4J+cH6/51/orYoi23yLLM6Ol/T+gxevCtOBkGn0b
            nnZ78BT9hujiMbD/8rG9z+yWmcDyJ3ecD284m1p87S0SbTTw4HhMa1su7SszhuTU
            aAEHAhBIXfVGPYixxQj8rEQ6+iIq32TQguH+qFJADMCvKLTtCMimgDzSdmkEGvHQ
            rDbti5YhsU/I3JsQz9fDFxSjm3ylAjltYSvLsq9T61rVfF5H89nKT9a9E8b42bBf
            edpJS1T3Fhkd
            =3oMT
            -----END PGP MESSAGE-----
          fp: CCCA3F0D6E841833AC56DAED48E4E0C7613AAB14
        - created_at: "2024-07-02T11:43:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6Kr4c7HLrmXAQ//bPKXUIeRmi2mclrRBOGK0wo9rfM/Rcy3eWc5imyRRJoO
            e1gyH/LPJQN8Bq1DAxNPM5Wk5GM0Fu9brXL3Jla7RTuW4ah9DM1dsFMiekKZ5J8/
            /c6Tqx/P6zS44eATcjWI/rcBAvSRpfOe29ZusjUwIBb+ao24mvBLKIBV5H3LUnVC
            GCLO0sP6IQ6y58i4pQ/NhU0R8vAoW6XpP3gb6/Il4WiBGCckt0w4+4mCP7F+SCqn
            SmglQGq0r5BmZL+HRRi3KsKtAqGWpulw9jGVyKl2krR3rR/y0SBXJGVYxeOvwogb
            a6mcM10qNxiQBn/fN+bTvtMywyLxZSeKhXNXIFlBXVaizilTBad8/llIxH+GU2E6
            pxl31yiRD726vAlPzEXVIzrkVCmro8xqnm3vwHLIcPosVpZAnNvW7pj0SBcwgSon
            n2IO+RIkftidJCAbvBNq58E9hos5w6Jn5o3RPw3gBwrUXinGf2GwQdpl2kpcpAUp
            H3Q78oYfdeis+sW0MoKY4VzulYS2CCei6m1R0TYsNsnNEC9D7AFhBSGqJN9bQMub
            UjJVc5n1B8414wZEg6XevBkNcD5RmYFW2anjCaZrwK20oA0pcoW1/SLQmrIXBhK9
            prKwiwxYlWidpJIb9wDBCe2IFnmqFYM03VR467TaI/GmcgunTFVYnhKN/+FYYT7U
            aAEHAhCDghc+VqiCmOKwgnyJNs6pRFjkDAk1kDuxJwJIgrehpFrFdqZ5NHLv++Fn
            CzCcqqx1U+wujg/Q5f1Rxmc9XcGJCZz8HcVbIoNW1TY7KOXekV+zdhE7Bhma3i+y
            hJIaSUPvXNlz
            =8gTR
            -----END PGP MESSAGE-----
          fp: DF71497C07110D584ED5D379CB3A922F8FAE3D50
        - created_at: "2024-07-02T11:43:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/o5Gaf/w6e6AQ//Vmc9Bb43xHLMKBB0FKB4YLwv7OPXSpEWach7k1h/VUSS
            LHboGmWwB+n1VMQDPo/g4aY3UmkwP0LB3kFJEpxXvQOAPnehbyM7/SdUfAk5ozIN
            STcyEfaJ8DACO7lV6ctZOuso+rhLTzCz9JQ3lha24jdLjifrMaP8BNBdc7OVbCxr
            hglw8yPea3WOOpBDhwiDia+93Or32Cz7LeQ4xMpDRVQ6n71PzxJhce8quAn2Ra3O
            m/aAFPAWmL01gK7VfSqiRYqvky5Cg7CgUczf0LMvmJ8UuwN1YY6R4CgHMN4mneQd
            hKidsOap9Ln9sFEvUBaiJ2Vtpf7g3H4kO9euVVJLf4+20RY/mlAJ7vTMpKFXm3Dl
            IgqHzUi9VrqUkp+daHu0bytG5ossZmZIuxhT80dMW+8z/L6Nz9GNKspUqMweV88F
            WBtGv7Mt0UJCkx4ruQkPW/Z/gdGQd97pcNZqzt4ecJn/yds1mW0yp7morCl6szNK
            70WGRb34daFteHI81gHM91rq+T5+WluP7MIBUHqaw3FmnqpGvuj9WGq9QcNeLj5L
            mizyFKOY8ZViTS+2aPob/C+aIyUbLuMV+4yw9wiCfiow88pk7q4DiVsPe1lgX9Td
            bxkJlLYOKfPVibfxnwfgMsU0xTCkLXBQXY8nocsbkUWCpDj1Uwj16f0m7vX3y+XS
            XgG272y/jGTgB6k7fRpIsFsjz2bSpltnfaIooWe1QrqlTKocNBPDvmukJBYP7W6c
            KFDQtLEKoiQ2TTEpreuPmo0gofRa3lww9mH217XcaFPlyS9U7qdrOJZqHPHNVmc=
            =s6Ln
            -----END PGP MESSAGE-----
          fp: 5AAE7807A91FBAA7A5DB246B52A2E96A7268BCCE
        - created_at: "2024-07-02T11:43:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hE4Ds9lh1tfJlukSAQdATVXRhIyGIka0oOS/HpVNvQhGrb+5EnC/DUR3vaP8zEYg
            b/yYudviCevICtOOUBf26EyQaiCI9te53e/KCsBmLIzUaAEHAhDuMxGL9SC18IQd
            wZUUewYQyaxnlJtv7QmF5KgKgZAayPhszR7NSCQfO6i46GqBjtq29xgTl6qjTuzw
            MiQRrT5mPfJJtddLdLf8yb/3Z7lqxF6wqk1h48VC8AqaHfwdr686DoEa
            =FutY
            -----END PGP MESSAGE-----
          fp: 6A413E28286599A84595529EB2F65CBDF1C65D3A
        - created_at: "2024-07-02T11:43:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2VTGvlVjirjAQ//YYQkIaFAf4o4okjY6p0bvnpKcW4FkGNr2uHfoPz8/jw7
            caNWaVOOc8tdryIfDamZyblsIHgEHEFXIl5iP2IOzUuTiUwCjML2+FY+ztPc37BT
            A7KHXddqzqbmacN6sSI4bFgxQqQ0nFNLS0kTbUaYOz4btIpBy6lqx540BP8JCgpN
            KLTmHKsJQll/XNJqemaNTSgx0bpcBvS1BtHqpoKR1JvV+HxMLCOVOYX4fJklkfYp
            M7r7P5QeRGgjXBmJsk7TRJlHFtMpjTgcXxaIpLqrAN3l7n33t8S14KxqhAA6Qilu
            P+8Wvd4UklMJ5GKBUAwMswI+dOaFLzNdKVGtAy0o6eO3uB0q/51vMRve9HnjEdUe
            4ZU2rljegVLwWLcYTXHOh/0Cvum79XdD0vT8cc1McAg6CgRWGxkrmIN3wodbEJ/j
            0J2/6SLd9TaT1Q1p0oTpxuKvIDi7iUF+Drr/R9afIiPn4pAW2JS0D+6KvQHgJITh
            qrY/cazyVJVWJmmKy17FIxW2gjqHX1CVC82vgDRQCUE5n5AkXM0ZJxfYQBiT26Ct
            jcUdrUJ1GDllUVOzjam8eq+aGXnxFNDTUgAqqMoZEojrO/1GefxhNco/h8IzQA+D
            Kq5l4ph6eSRtmBcsnSS2bDIU7dEAJjIbEKARLlEy0RPO+zhUGbvZcFGZYIEm5O/S
            XgER/i+EO7lvaApOqwJD04ts4RaRWBGD4HtRRbo1UUZQ7jeBU1MXthr9MyE84XDt
            G6GaNFmZJVMt/zmwAndyEdZM+ceeq9scmmq4J2/n1qs0MqN1Krc+ychxwop1uMI=
            =S+Pn
            -----END PGP MESSAGE-----
          fp: D48108A56B0EB04A40DEE96775676F49EAFAA9CA
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
