---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kamaji
  namespace: flux-system
spec:
  releaseName: kamaji
  persistentClient: false # hopefully this mimics --wait
  chart:
    spec:
      chart: kamaji
      reconcileStrategy: ChartVersion
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: clastix
  install:
    createNamespace: true
    remediation:
      retries: -1
  values:
    #    etcd:
    #      persistence:
    #        storageClassName: csi-cinder-sc-delete
  interval: 10s
  targetNamespace: kamaji-system
