---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-flux-config-ks
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./prod/flux/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
