---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: openstack-csp-helper
  namespace: flux-system
spec:
  interval: 1m
  ref:
    tag: v0.6.0
  url: "https://github.com/SovereignCloudStack/openstack-csp-helper.git"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-os-csp-helper-installation-ks
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./prod/os-csp-helper/installation
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  sourceRef:
    kind: GitRepository
    name: flux-system

