---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-ingress-nginx-installation-ks
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./prod/ingress-nginx/installation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
