---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-gen-installation-ks
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./prod/cluster-gen/installation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
