apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:T2H0U5jd72YJeELSvJmR/q1DtB/M/Vqz1JCTwuJ8OOJndppQ8FueLhYtrdNJS9zjJbkghIY6MG4sAGNs/3awrt6FOmHFYlejot6rpkpyK9IG06xhX5B9siHCyNWxTHSLKsxckHw9pdNe0ASu+z5KPgEpftL0NyajOb+dpIAhWsUfj20gu6w2A3a1OKFi5wWFRSgDOGIcUE2Bv8M4VzdNbgQsXnyIVZfoipzdsq/6r0J8eNE8xBFVQ+7S6yJp1YwbJahK4zAscbkAuFpeG7tZOVCiCL1KcIMIlhonFSvc3iNfbqu8c7v996eqvOg8Ra74wvEByTnc4GJtizrkv6qM7bfMu47Y/ZQ9IamEfUaSMxPJ9KXcp6XvFOWGOozxhdd3BKLvKbwDhN4Tla1HlsYSfgPBC9l7KDIPzmZg+PP7h26E3uh+1IsptPgDkLxLMK4SnJHrwF0Y9+JT1qHebV0OKlV4xtwqdFEpH55IGiKer7Kpu/qjqenG1s6hkMpphw9aXvAK6fRA2AA1bU/6HQTCsZyT2w0Aq0MbKzVZEejQwtUKnyrXAOY7QirSGjktEbiEBHCKkKDMfWCDf0aUW8b00QIbB0sKvzpNnAisBWkvcW/H2uSAh51UnakGReunCCnh7M7KkTl8kFpvo5Dl9EF3Q+eOdw7Zqgni/0zUf0/ir2tjgnaLH2DhWwog/RGft5KiM8LOS+TGthDebBsaHiwUe8P4k0wYkZsh4Vz0eRaOZ1m04Ep8t23jzsMxJRbOKjbEJcmc4EwOqzLL/XpefqhxUcg2OF4GkTTaYm2WHbrl/MOPNdsb8hEbSnKDCQ6NOB39blyHnB9yleuwMMUac4UxfBFwUX2iYywGf+pNhp383KtLvxWuK2pfkgCWKMD5Z61+ht9tz+R2viJz6TFydhHZ0UVDTKz9LB9jz7NIOLyPLBo=,iv:AP+BX65OzfgK2DAcbzB7iEK3E01de+WgiZ2JASM0s+k=,tag:g1qnlrS5hs/0OvmNvd3y9A==,type:str]
kind: Secret
metadata:
    name: monitoring-values
    namespace: flux-system
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-03T11:03:32Z"
    mac: ENC[AES256_GCM,data:XH+AL8PDSVNtSVhBmvvuRP4ONb/VLmhWXTpNncd7w6HMXrnF+BtntQtYqH8lfpD7awcdt5hvKReEtRepYdzVRtEvQYSiUJJDvSbJcDkFgCkXnfoQ9UC10R4QD6gBbBBGr0p2SqkTX1QNbRAOm10BO266EacHj8ITYzypCXaT8lU=,iv:BZzeu2eFfHd9jTwxZjEL+LwUrpExgv/9TIN1vruZH+E=,tag:t/bd0YVgtMiZFKBGky1i7A==,type:str]
    pgp:
        - created_at: "2024-07-03T11:03:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyBxDD99NeTXARAAzTwEdNUnJDHqt7nWf6g9TluHgHDjZHIqN3X3w4O21Aqj
            Dzxr/87DT0BYvMvDI67fQZKID6eW03FXJR2od+cY2GdJ0K5ot2OndeDgNmOXHcu8
            p2W+lS/r6t/FRdnvkEPUPJ/EZlHYv98tH2ugefvP3QLigExlp2MYCZ3THrOxCvL4
            MVpPWTbX/1avk4yEmPdViV7lNOt5ncJKBKCtILTDnpV3sXxt6pivZpJ/Orj1dR6T
            Wm72sslaKnG7FxAwJ6ATOHDtW68BEi6DL9OjIl6piQFh6+XL04+pP2ZkM2OY0Myw
            spQFbauUINNUfMd4CJ174FMDisFp0eegn25PBVjrloRIVZ/lD0eVyxhnGFeV5zIG
            6msk3SnyqH5TCsEpfaN8Ls+JummfwhZQHesPKqOmqHVBD+yC8I40m5RfROn3DH4Y
            VdEUYKOcOBvI5zX9WGnskQw5BF6dtTtFFQrfqxXEb2PSPGevSmooJUWT48PJC7+G
            mUmmK9pQafH2hSLsHl7AuqOaBqqXkZnTNYHRKXINjVnBRiGzeSMpBmsrPufJsle5
            b80sIUml/m5CeM5S9EsWOV3obMy6yCw3vxZlGY5DwMdf5EMDihh+Q2QFntjd+ozA
            w2snXX12YaYJUnIa7n8uYGFXqjdSAarVtgSDJocPHowZuisDF15YaMsfZB1dbr3S
            XgEscbdsUaBolp/RzeWR5h+NUm6QZc2b2xON84UvD373/ubZTvwcTe2VYV93wbxt
            1ncOoX0JOjno5ona/X6vlbyObHd3/wN6hAxRr16o1ICTn7cemFhobPEF+BZBjyU=
            =BfHB
            -----END PGP MESSAGE-----
          fp: CCCA3F0D6E841833AC56DAED48E4E0C7613AAB14
        - created_at: "2024-07-03T11:03:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6Kr4c7HLrmXARAAnHZd+xBVxZiuFXNh67rmjGmgLpe4AGfqEqjplbuiNZZ3
            G2Lgg+8IVGL6b0eEO231yh19EUB6BidQIL2p0+0pIVALtGRs5YrlqvO9QnrNYPtn
            SBWt4K2AtVIeYV1BkPphKNAGCcqhft9jzzWYKf4j+nagNy3xhRNXs/N8PmsP2h+6
            Q3gD1gigaHE7fGuNrRwdw1UkYkEzq9qm3GYbpmXgItOGdOviX8Kbll7rkOOtVcQx
            fESFTpkJxwbWAONkpbNxp7DHwIwbdTzZEgEO0ypwB0Yk1LOhcFQLSWPP/r6LUd22
            S0v0zhK9s+Tt6EaAvqNfaXmj74dkVhuk+osyxBPg+/N8YSl+oru62Hq5fLYxk5zm
            oB8tVuEkLzHZxLrR5/fpFzQYSu5APKvytFYPrAaT/71AOYk7FekxADRwg5ii0gYJ
            unoJshd3I0SfGGNNK+rK/CG8dvxS5HtmiwXfouhDPw0RmwVCO3hN5ZXRMlz0AlpY
            38TY2cWjJot3A8eDf4wCKV5C/9q86ezNj98tYGmSwtH5F6IHao2+Sse8JH9duKve
            NhiFieZihdLFwE2ZEVASP/+2Hz6BzDQBa5tqF49gDPobkZQVDvaGL4FAeaV6aGBQ
            t3kM9HrdvjYGNYu01JfALmbyylPza5x/+dyDmt6kP2pJfnVB3VcVFJH7b3h5G9PS
            XgH92d164kMUoUPo2aBZzLTmfeeaHSYDn56jALLJ1upCeeka+zP/hC1JdUdFcU/1
            +OBqc+g+n1iH8dwyhfZaZ8NyspWYMc0bPa5oI8ORvjoK8a4WawesvnD0NPuwGDQ=
            =cDpJ
            -----END PGP MESSAGE-----
          fp: DF71497C07110D584ED5D379CB3A922F8FAE3D50
        - created_at: "2024-07-03T11:03:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/o5Gaf/w6e6AQ/9F1TFg/89gXtUydmJgnX7Ht9QqFdtK3EAhdEBD+Nc6lWL
            sI4/cjWkgksC17ouM5t5dCKMgBJIPolFerxARC/YpnJCnqWipsH27XZKsOZVgZbD
            lah+O0cwCHpqEKfzRxru/S1Q8nsTvddkSHdE4MzqYKLz1MXaRcJtjYF91ara81+e
            HDP1DYwnIvGDVGxctMNBTwfTcjlhBkwonZrTNiHRlbbpuV85hum8TvcVS+4sPR0I
            BivPeJC8LOpxcav0mgyOCzYBvpbhSB4ekPDMdXx8rrZU30/DIvTEzhtZ1yNV0w/j
            1p7YcvS3YmfAMqC8qoHLH2ZA6YDOOTgvLaF/jpFxWFOSyf6wxDLIkB4KLxlB+Qwj
            JJ2IXWT0OhwpjplAeOqqDtcIrwnsfFGCsVaugoAc6NVm1OJmnX+afHlxMOgrLCNl
            da2eMi2tFEPeivvH8AKgHC6B4hBObo3SkcTNQDMVYV3G4QJC3H/3YJKd38Cssgst
            0vXxEvdrhhKBu+TPCy+nnbPvv+QwwnYfJghaKhaCi/9Z2V4ksiomGcyBSr2+pNP3
            fDa3arY7czBfrnxHG2IheGmSttUvnaGoWoSVTo160h9os2QsdUERbTtmSFRRNlcM
            co9RbLQfxJqCHdiJwAoJ/ociaRNC20GayQqpVy3vOCjKpbdU+WHE21z4+/JnP5jS
            XgH3zcCYAs9Ko8JFMc+zyTTo76tNX4Xva8Nvz2hquYV/CnuzKdGQhEB7xuIUmcPt
            upeI1r3gbnMMkBFVqWmbQyhC772wACrRIuqvfveGNR7MYqbRLKKAoOA9Toa18oI=
            =6Jph
            -----END PGP MESSAGE-----
          fp: 5AAE7807A91FBAA7A5DB246B52A2E96A7268BCCE
        - created_at: "2024-07-03T11:03:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Ds9lh1tfJlukSAQdADNg5MsLmsd1dfgn+cSuwmfsqTAA3XEeJUY8rbbbiWyww
            rXdvxUC4U6+SESMMu+WoriJnwKdqcvsjM082JRnUCl6O0a8jcu2NnAeXxG91Zfx1
            0l4B248Dz6rNQof8IcoIDPMmnhYUNiBySAdtEf7J6CA2E+cPMD5e5XDD+Y5+EUzB
            ktsT8jg+0/GfZMeglrERIUJ8nyyXmeRXtzxXGELm1LsqonEkuWTSPPFCje7ke2wj
            =RzSr
            -----END PGP MESSAGE-----
          fp: 6A413E28286599A84595529EB2F65CBDF1C65D3A
        - created_at: "2024-07-03T11:03:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2VTGvlVjirjARAAoFJk+xjuyBAF6CU/Ep7K6Sx/DGqv8A6a8BO0I43PAqDK
            etB23DcapXqSlqaIBy8UTU7IxYsHWSAG67pd3XST+Za3pBaj7DtIhaLjB/kiDKQV
            ualbW6GZrQmJPKZdfqVtib3r+05qyaWz3cK3+HTYNqFiDiyclBqOQIoZjiiUbxja
            Gt8+5tz9rKqZ06T2jVZGmz4Zmj7GkQreDQYC4ImrFedj+2wKUA/HxZ83flLM9+Z/
            6E7ETGX4oWlvzS3WfPC0/yQt26OIHrs2qVTAKBNczX67VEgrawv7JtvNUUyj0TXX
            Rnjjs4NwjsrqW6cgxS8E6ZtXPEVxJdQad1k0Fn/NzzgDkdwipxLrxqwtWqNdKrea
            3duB/kJrxP/PxLBtT2J/0ZoYzDH6/w+4P/FLVB2VAKy2yILXfOiOmD5yXRwYD13+
            Sou8dQsHn0xF8hoMVN88mPv6R2h1twpTr8sGYftvY3vzl3wxvDW5jwC2VC7n5ScZ
            VwPE5F8M4jocJJgUgEiwEN24eoQxaX7yRfVcszEZPJ8CbP/PQdDriV9YCFrTY+5o
            rvgLmPUmO2GKetsxhCM25ooi5hFC7kf8sUh2Pe6l+STsVQQ2GrhkUGSqFjQKH2aZ
            bIlbAt8qq8p/w0oblVs0I31/ILCxJd+ekXqnaacvGprSucRbcdnxisRp2y7GwB/S
            XgEu76sstXxYCdccnpXEuPaNm2EySz1EM9I/Ov/Ww7ljaNLjtIU4ykrQXC1UeZcs
            t+h6mDDvnMrbMMHY5i06bFvjybeX8An/YAr9jRENfWfEck+Fzf1Ni1JKT3L7CQo=
            =uG88
            -----END PGP MESSAGE-----
          fp: D48108A56B0EB04A40DEE96775676F49EAFAA9CA
        - created_at: "2024-07-03T11:03:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA/CESpP6bvPkAQf/VZ4F3K/r7Pgnw4v6+RevLHDMZBwBoBIky2yeHCf+61YT
            bYLo0sJ1xwAVkgJuGn57WjQJTdVv/Z8Wh4sYSGbVgBV2C4c1s0A7ya4FXLjM4kuR
            Fg3cwM3mlAM5AgoW1W9EMuR64FvWpP+QujF+lxyXzJTOcKQWbMe/a8duJzxIbjLG
            Kzk8ZbkpkZaOldrCvWYnYEV0sli0RV8OUviK3FsKIihLsO9qRzT2lDALvy97uceV
            yYs1nHPrejnguzdRC0J4lMwMCgvNr+A20N09B/TF0zbYTeWkak/odwfW+W0Pr1ki
            QFV9ENlHleBtiYui1UcI4c8QHuXUW0K1bwhXAkaoxtJeAXxAXAxpuWs5ymSOPNwb
            4gxeeoF5DkgDQ2vRZZgjBoKGM6gFFycctz2MC4tpfU03RY8hnfC/FFF3GMiJhAsc
            yiftiKWCJLQAUDUYIGSA90tYoauTIArf9u9CkSZ15A==
            =FRFR
            -----END PGP MESSAGE-----
          fp: B6829414FCD33331EBD08EC3F70112A73CB97C21
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
