apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:V4jtvtfgO7gSV0aItnyxKTnkPNncrcvGOru6PY/EElc34KVBOdauks9/ZcnFvFPJI3yIPQlBgzsO4dVY98T+wcX7V/SBfwfxWI9/DzMgieQt9Dpa1drieALIt8fIijqe1PXZ+pFwZiH3XipDgIhJDXowSMMlWSM0bRDmdkmNVxGKsh13s6JjQ6eYdbbCn4x2jqcdR6ydwv2r0PheaDLB7AmjJEtyl0JX1g2DD7v238u0m3UhOcfZ5GjA2premWTRK9f4zELYr98phUCB6+kFAstT0WGHFW7i9llfsm2JkJv425jXXT1plIMhdKDfI5Rsn7WHmox3xEOvIZwltarThhSAW93zakGGptdSbW6VDcTxl1134WwqHuEd64NTG7wdsnQCwfrqoz6NRfnoU8ydq/1gqcZwdUzH5QUV1inYIMnpYfflS7bLkI2bhLMc5JtKRRROk4FYgGQRV7L6MqI3gTKTbhBly4YHBvhaVYsuiDAyZU42lWH0jcQQW/zOWjszH7Q13Xe+b4wBJADQfmOU/0jSXFBFw3syl8L3ies9+oCNmWyF,iv:uNx0eeqQdrQ6Kuz802Q3ateGA5SD0WpUctuAGDs51uw=,tag:yKRIFISfHibEUMcOexSpzQ==,type:str]
kind: Secret
metadata:
    name: thanos-objstore
    namespace: flux-system
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-01T10:10:57Z"
    mac: ENC[AES256_GCM,data:gxy/m9DJ0BOOYSTjKzQl15tQG1cZ1bpGODMSayGNKdPEuF/24t2fGpIfxA/BnTIcqZ+AQPK92EmkIlmcgt7FgJI3n87ubrVKizFGVX/h7oJLpQuD39FWcqNnxT5eCiW24Wzo8GAI2ghyUwkqbkc3MZaAUuyF4gYOumb+1K5IHnU=,iv:FJjKr9MDaVtvCFvBfmclqseT15mEaEa9ScPtQ5z1gso=,tag:KaPhMFO+Lqpj380iW0US/Q==,type:str]
    pgp:
        - created_at: "2024-07-01T10:10:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2VTGvlVjirjAQ//S7CfFb5D65myyg/kF8lUV0yhXCpFpUObHyeL67i8F63l
            AH0F8+Sc2xe3pdYv0PmWIDXYSli971XbD2G345nXG3I1ppy4FlU7ghI3pX5CJ+xV
            T5fq1sEUKUdGvVzZKCZI9eTC40HvxmGo8qBmdEGC2+9gQFCOEHAMiUv1+IX4PQnh
            gYzE2fthoiyb0o+1j6Ev74u00mcp0cd+7RwU4+h+oOy41o9IdA0H+vjRnOwh+xAq
            ySVIlmzLSaeq5GUBahG7Fc8AwzNPQmjrQntGbv3jUJpou9OYTnvk6UVsYGdXtNmJ
            kGEcNcpKZSxHIRUuE/+YPT41ro+fD4Fu21JyXtGyfBmkjpaI8BAb1Nn3utFLagTh
            UwubXFUGlQEPzYBwXePEZoahDHxT7bS+hL4I+l9sGzw+HVg5woCYAGXFoAhAHnkD
            O3PB3/ixTUpKbRtEDg17GlId/CsDad9fJkYDFfNdvPXAjI7JYE+Kc2KnsqdnEeHN
            zQk5R+0FIO7uWBmT6vs6CpAJZ3599bAG94pbkj1mJXNHQQkYl3uej+bBdfZAiXIT
            5sOH5Iy6x+SllXIHnnCJlgR9V+eNMb5+plYANsRrsF8mL2xOYs98sn2M/A7SJydh
            FjkhGz/uGCK6eTNePKssyeNlN5155dPo/YdwVVze3QctMJC0Y0gNzv9FmkNICnXS
            XgFaD3g8wf5iHgP7IxVN6GKUlWAdPysR4AC7bFc3L1+NrWkQP5cb5xjbvWDIBJZR
            68gkc+WFoF0VUMB0gmQKsex/balQ0TgGeSr2NFwJNSn4eTDWdB/B54xNEcksDSQ=
            =tast
            -----END PGP MESSAGE-----
          fp: 75676F49EAFAA9CA
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
