---
apiVersion: v1
kind: ConfigMap
metadata:
  name: values-workload
  namespace: flux-system
data:
  values.yaml: |
    thanosStorage:
      secret:
        name: thanos-objstore-config
        key: objstore.yml

    thanos:
      fullnameOverride: thanos
      existingObjstoreSecret: thanos-objstore-config
      bucketweb:
        enabled: true
      storegateway:
        enabled: true
      compactor:
        enabled: true
        persistence:
          size: 20Gi
      query:
        replicaCount: 2
        replicaLabel: [prometheus_replica]
    ## FIXME: Thanos query is temporary exposed via (unsecure) NodePort, see https://github.com/SovereignCloudStack/k8s-observability/issues/32
    ##   Thanos query should be exposed via ingress, see below commented section
        serviceGrpc:
          type: NodePort
          nodePorts:
            grpc: "31050"

    containerLabel: &containerLabel
      sourceLabels: [__meta_kubernetes_pod_container_name]
      separator: ;
      regex: ^(.*)$
      targetLabel: container
      replacement: $1
      action: replace

    loki:
      enabled: false
    promtail:
      enabled: false

    kube-prometheus-stack:
      prometheus:
        prometheusSpec:
          thanos:
            objectStorageConfig:
              existingSecret:
                name: thanos-objstore-config
                key: objstore.yml
          replicas: 2
          externalLabels:
            cluster: "moin-cluster"
      alertmanager:
        enabled: false
      grafana:
        enabled: false
      defaultRules:
        create: false
      kubeScheduler:
        serviceMonitor:
          # TODO fix this:
          insecureSkipVerify: true
      kubeControllerManager:
        serviceMonitor:
          # TODO fix this:
          insecureSkipVerify: true
