---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-visualizer-installation
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./capi-visualizer/installation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
