---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-config
  namespace: flux-system
spec:
  dependsOn:
    - name: capi-installation
  interval: 1m0s
  path: ./capi/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
