---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-installation
  namespace: flux-system
spec:
  interval: 10s
  path: ./cert-manager/installation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta2
    kind: HelmRelease
    name: cert-manager
    namespace: flux-system
  timeout: 5m