---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cso-installation
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cso/installation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
