---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cspo-installation
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-installation
  interval: 10s
  path: ./cspo/installation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
