---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: wait
  url: https://github.com/SovereignCloudStack/moin-cluster-config.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-config
  namespace: flux-system
spec:
  interval: 10s
  path: ./flux/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
