---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-installation
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/installation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
