---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-installation
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kyverno/installation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
