---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-config
  namespace: flux-system
spec:
  wait: true
  dependsOn:
    - name: cso-installation
    - name: capi-installation
    - name: kyverno-installation
  interval: 10s
  path: ./kyverno/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
