---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  releaseName: kyverno
  persistentClient: false # hopefully this mimics --wait
  chart:
    spec:
      chart: kyverno
      reconcileStrategy: ChartVersion
      version: v3.2.2
      sourceRef:
        kind: HelmRepository
        name: kyverno
  install:
    createNamespace: true
    remediation:
      retries: -1
  values:
    backgroundController:
      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
              - clusterstack.x-k8s.io
              resources:
              - clusterstacks
              verbs:
              - create
              - update
              - delete
  interval: 10s
  targetNamespace: kyverno
