---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  releaseName: kyverno
  persistentClient: false # hopefully this mimics --wait
  chart:
    spec:
      chart: kyverno
      reconcileStrategy: ChartVersion
      version: v3.2.7
      sourceRef:
        kind: HelmRepository
        name: kyverno
  install:
    createNamespace: true
    remediation:
      retries: -1
  values:
    backgroundController:
      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - cluster.x-k8s.io
              resources:
                - "*"
              verbs:
                - get
                - create
                - update
                - delete
                - watch
                - list
                - patch
            - apiGroups:
                - ""
              resources:
                - "secrets"
              verbs:
                - get
                - create
                - update
                - delete
                - watch
                - list
                - patch
            - apiGroups:
                - clusterstack.x-k8s.io
              resources:
                - "*"
              verbs:
                - get
                - create
                - update
                - delete
                - watch
                - list
                - patch
            - apiGroups:
                - infrastructure.clusterstack.x-k8s.io
                - infrastructure.cluster.x-k8s.io
                - addons.cluster.x-k8s.io
              resources:
                - "*"
              verbs:
                - get
                - create
                - update
                - delete
                - watch
                - list
                - patch
  interval: 10s
  targetNamespace: kyverno
