---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: capi-visualizer
  namespace: flux-system
spec:
  interval: 10s
  url: "https://jont828.github.io/cluster-api-visualizer/charts"
