---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: capi-visualizer
  namespace: flux-system
spec:
  persistentClient: false # hopefully this mimics --wait
  chart:
    spec:
      chart: cluster-api-visualizer
      reconcileStrategy: ChartVersion
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: capi-visualizer
  install:
    createNamespace: true
    remediation:
      retries: -1
  interval: 10s
  targetNamespace: capi-visualizer
