apiVersion: v1
data:
    aws: ENC[AES256_GCM,data:XF9Q+M9Dm1jk9oM0fEE6nA/NDeMpyaFjSv/hIG1yim7sfc3Wwfd+LXcY3e+6fK4eiivq0jexxgs2bHapBcpbH4GB3QCrTBJ3IF5AtbPjzkdQr0RHTU7o6ph8UoV8Jaxt8H4iu1xus3nXKtlJXIV+1wYAfDcEC4S6UBunRc5Y4QaXlrL/kRx61fUDI33JFIrXTwymPgd04S676re4,iv:qIk+2XWNe6SP8VWtHoF2KN+92mU8XldAh9uzAc6t+5E=,tag:zg78kjYlY+xIz2m8XkLcsQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: bsl-credentials
    namespace: velero
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-20T20:10:11Z"
    mac: ENC[AES256_GCM,data:V9kAo1ZVh6RelXOriNfzlAbESFDNrl8K5RshOxdaGRWqHpDBNiYFWJS1jgHMobp7poSflCLLRQlZU5VeGL0YcZ57w9XPZryF6Mf5/0Xtcei68wYVVBgPvYyOTRZA//IWlSwNDQeuJeJhXQPTBbt/JNhMbkpju6ypYg6F/Ya8AM0=,iv:vl9zkAgxrE3mwXf2P6cE0bgE9VE9+DPx/hyEKv9Hiq4=,tag:nsdighdu3E4yTn2MCTcKRQ==,type:str]
    pgp:
        - created_at: "2024-07-02T11:43:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyBxDD99NeTXARAA3HM7Ehu4BtnY6cazXKdi60zHgX+hBCqKiu502XsiQqbr
            LnFlTfWjnsF7AxPnj1HnSL9Fl3pm+jNYTBfGfar/ExHLHDeYO+vy4YcSjJp4LKtp
            rKK81Q5SKZ0TnD8uIskQHDM/JcmjDdI3DjvZ7s5FMhnDVgZPWS7ZdYCeYwXb8VLW
            XcY04FDYzk37NKh3uXbKImtxEulY47+ij8TIBdwgj/97eRyjTMLBkQlAJ2kRMRa1
            Fb+x5cIPgCxKTW5bLU4R/ngtNBgjPog2r00m3yOkk4gFXyD2OETzFH0h42QNyENm
            4g4mS0j2+NA1SHeHbkuueBQmx6YLdF5vgd4nCXTtXusTsBQjZnRpX4Kcr13NgK1e
            +A9AF/8yDuT7ENlhpXV9VOvlbDu4SNrd1OQEgdstgtO3jcIeXZ3P9FtWq20vI//a
            m8bgQLSp4YsmIe2dm2YhJbrSX0TDEDNN8+T/SI4Y4ZQB8fyUaMFrBK3ylGnju9B+
            Hyujpxmb7fTnQdRJqdLaORn/nyllm32WgA2xKUiCiHx1bbWZGCYevgJnbz4PKhR7
            x6YnRzeG1ku+psBysZDnqWVRsYsc65kx3k9ZSut2PnNxLPoDhBudrkjv9xpnSMf1
            VxbMqPNMQKF3++/TjUEnGckd984xqZVBx6B4QCAGZEXUIVV3hTxEXEX5PWV4zLjU
            aAEHAhD8YuGAApqW5N8FlQcIF+ieBC00TJv7vmZTDxUJAKNwhzdYIsx5H09Oz89U
            LvEb7OBKRjWDCD97abqhFAru7r6XNX1dXNAdjnnz/34eYR889+2AKpgNZq8IsV/j
            rjHUTFPOSApX
            =2b2c
            -----END PGP MESSAGE-----
          fp: CCCA3F0D6E841833AC56DAED48E4E0C7613AAB14
        - created_at: "2024-07-02T11:43:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6Kr4c7HLrmXARAAsEnxGwP3uqbA+XL/2GQoCPNOBnS4ZFLtISLdmxviDM6P
            4fCKlE5SROdnEJ2bky01GvGthFDtTOu49Q3xHNkg+g5JlPqxJEZYLM88td9r5G1T
            zh5vPQ5TAchIscdlLfYWX3k3jMkBACjkTcNL6UsFX85ywSCAb1mO6TDvdhfefldF
            V+Op61l3L43BICmn1F5PvWKMbVcZ/Gm9D3ahzvPDv500cUXWO453RdeHmxBTicvs
            CTDqQD8UoG+dK9dOGrWHAx4OeAWM+MNx3n7z5e7RuLS+NcQ3UgChTK1K4RiRMrsB
            MVSRiPdiPMPAwhnXcDPoUJzh8BE7i9vhD5ry6q2qr+M1spg5jEaCke3SQLJKZhkM
            HP+IKwTdsPUrWCcjc45oMBQiWspeDUjQNEyZ9P7/w1qK1woaemHKH8cChahMFZQ1
            kZ9W4bhyO02Y5Qc5X0bOtOQU/T2oaMOnoAMCKhRyYKA+THw697hk0tqOLFYt/wCk
            GzGLKX6AQNMT3cqqQzmuk1ZBGDM3ZO6RSpG41yvWCu0L5BjGvx1qASvoXrBjOeIx
            pRaKDgQ1sPctN6DzOxkbByhnXokkXyr15ERbaSvZRrwtfJBpCP3dhyP6zFjVoFNv
            p8v8AkkV8StYl3ZAQ4f3rBkuU0iXHMUZsTRTEJjy7LqT1cOHshbQGJjk3RJzELfU
            aAEHAhAnHYsAQNkVXSMFSMw8bke/1XvPMCOZ66xGcBdPXy3gEEOxY6RxC/RKPbn5
            k+M7EZIDQHfyBvKWp9XVzR/bHdYQzYx95ic+9bvM4nzqIsIpQjN8cNLErjWsYrN2
            vP7cuup2NRtD
            =tjuQ
            -----END PGP MESSAGE-----
          fp: DF71497C07110D584ED5D379CB3A922F8FAE3D50
        - created_at: "2024-07-02T11:43:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/o5Gaf/w6e6AQ//ap8mT85fcd8ueJ/0/+kPjO1M9luKJXMR/TVn1IN2Vi9F
            GbxMe5TPFXAvTtUKGgIXAlldfa38Y3c2feIshEebII6xq4S680QDuF/DFmFRr/Rt
            6qYQIRc9giIA+Ad0U/jHRJmHa2mFnfUelqzy3uiMyHc/w+1s10iUNikCfYIAOYzK
            WxL4248HuoG5RPn1O1pKVhnSSe/uKrqO+MK38HqAmatRlNNhE5zZ7mYt+qYVfzEB
            jMjxbyJgwVgmHkznMzNj42j+fxxjZ3dZWdDRKHX9fg33D/ttJV3gZ9XMd0UT5USt
            SQnwQ0OeNq08QpBsUCqsVY5iJaZAOZZm3czmQ1pAdbRhS5XoSm5Fu93hetiPJE8I
            O/xms3+DmvyT08hg6ga3QGuB3E/t884Wv3w8NmZ07+0nPmR6MysH28h8pA+k761T
            +FHqQ0GU1GwdTGjCopCSd1E5wPbyTw37QsMYGRlMp3Q9L/WQOWwyKoJ+2S2RQ7vn
            e5nefIFyvYrTwqD3FgdL/l+ddkuuIC5rN2UHFL3J7HRkQSLcq+jwL+1lobHjYiLA
            y4EiacHvbwW49sE8JjLe56kxAxcqiQlnY5F9kDSrUvdiFJHLKkgOi/7BCNNuxfjF
            IRY9gubVVhL/vct3WRZr/ihh4tT/8enDBedgs/zB+qKTyKOZ+0FfBJ/MTiYAcXrS
            XgGKSee7VxR3Zx56ksyHbZx70lSnn5xS8+++N4ofmzJZ+0ZV87SiBHhoH0QIwbDc
            MZHm87Dd7x8xz/OVZmVbbnnVOuzhgSyLSna5+7WViByki5QAVsS4xD4y4gpYOPs=
            =lj7P
            -----END PGP MESSAGE-----
          fp: 5AAE7807A91FBAA7A5DB246B52A2E96A7268BCCE
        - created_at: "2024-07-02T11:43:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hE4Ds9lh1tfJlukSAQdAsU1dI3vq/nNNuO8Azq9IuaiiPJOl6M5vpkzbE+qFu34g
            8FW3mjJAInhWScdapUB1fgRA3zdiGB0ZTHvC6NnTu6rUaAEHAhA/+hi5uexpgmz5
            M8d8HQFLTS7VHIOEEO4KHDnm7ZaPFI6fqOrtc1KcMa4xXTwqVnn3niLE6xflg8VO
            1WjEDyu3Z8BU62jldYkvou2HSSihfkcPMkW0MJNf+Fbm51L/juR36A/M
            =s60B
            -----END PGP MESSAGE-----
          fp: 6A413E28286599A84595529EB2F65CBDF1C65D3A
        - created_at: "2024-07-02T11:43:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2VTGvlVjirjAQ/+JQZq7g0+xYVUgBOugnB69WxSvb3S9Bz2tGXH268GEPd3
            yuikBl8YDxTGnArSdnra6EBqYSOUEFeBqQ+UYZG8bE+knz5nlXT9sRyp3yvzmN8F
            Ouw4M6B/uEWLSuupnvS93GhQRnqDbfQzy5mCa4ZrNJJFV+jRGav3rnCa0kFtxHB2
            P2wVFhOLBw0lveT4P+8OnulEuHmDcij+1iaUOskfRfeMdaOzxHhk9XoeelaRLgDK
            5ydgUo8RUsnG8vvOqYzN4CN7SgpLdr0+dcz49XIcGiv5inVEz+vb9TZ//eyM9GSw
            yUjKVPIOn6iGlUTuQQZwdnlRoj/Vz1BGedDmUllBoHavTW4kQ9J8/xqMIC8CK/4O
            xjX89778IOdum/Dql+KWByOBzVqJAZOVVezIt2M1tm7kSQCZkq+E/tFMDKesQRJ6
            I7GwM3m+LxVD1xu/NfWCMy5yfhvyGXXJt52x8LAVQu73RVdFNhvO72sKzMb2ZryD
            AJaKRZT0lUpRO4o9fXGXLzqKxAidnXmtdvjVjtIYnNFF/vP69qblCoN6dPLZtB/B
            +H7EiKcKmZZP1l74g/S4ugi82wa5Y2kIPeHSXS3b3USu+99IuzVSXQta2Mpuftu5
            E8v0glTj5G6LE1czPypVLy+NMKI5VliAsaCZg3TK9Q5UsXiFkDL/7oV7+v6+oqPS
            XgFK0Lk6uYYqn4KDxHlL5IdRgQjx2avMScvSqmFf3z8AVCgvsnU1MlFQ5Jn6TKGy
            cLI9/Cd7NbpohNKP/NVXDBF1RV81wBT6OSmZhbsk+3vG8+OvkmkPXJmh7xLa+3I=
            =g4Wv
            -----END PGP MESSAGE-----
          fp: D48108A56B0EB04A40DEE96775676F49EAFAA9CA
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
