---
# TODO pin CAPI controller, CAPO controller versions
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: capi-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  values:
    infrastructure: openstack
    manager:
      featureGates:
        core:
          ClusterTopology: true
  chart:
    spec:
      chart: cluster-api-operator
      reconcileStrategy: ChartVersion
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: capi
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 1m0s
  targetNamespace: capi-operator-system
