---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: capi-operator
  namespace: flux-system
spec:
  values:
    infrastructure: openstack
  chart:
    spec:
      chart: cluster-api-operator
      reconcileStrategy: ChartVersion
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: capi
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: capi-system
