apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-supported-k8s-version
spec:
  validationFailureAction: Enforce
  rules:
    - name: check-for-supported-k8s-version
      match:
        any:
          - resources:
              kinds:
                - Cluster
      validate:
        deny:
          conditions:
            all:
              - key: "{{ semver_compare( trim_prefix('{{ request.object.spec.topology.version }}', 'v'),'1.29.3 || 1.29.4 || 1.29.5 || 1.29.6 || 1.29.7 || 1.29.8 || 1.29.9 || 1.29.10 || 1.30.1 || 1.30.2 || 1.30.3 || 1.30.4 || 1.31.0') }}"
                operator: Equals
                value: false
