apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    policies.kyverno.io/title: Generate SCS tenant resources
  labels:
    kustomize.toolkit.fluxcd.io/name: kyverno-config
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: generate-cs-for-each-tenant
spec:
  admission: true
  background: true
  rules:
  - generate:
      apiVersion: clusterstack.x-k8s.io/v1alpha1
      data:
        metadata:
          name: scs-cluster-stack
          namespace: '{{request.object.metadata.name}}'
        spec:
          autoSubscribe: false
          channel: stable
          kubernetesVersion: "1.27"
          name: scs
          noProvider: true
          provider: openstack
          versions:
          - v4
      kind: ClusterStack
      name: scs-cluster-stack
      namespace: '{{request.object.metadata.name}}'
      synchronize: true
    match:
      any:
      - resources:
          kinds:
          - Namespace
          names:
          - '*tenant*'
    name: generate-clusterstack
    skipBackgroundRequests: true
  - name: generate-rolebinding-playground-general
    match:
      any: 
      - resources:
          kinds:
          - Namespace
          names: 
            - "kaas-playground*"
    generate:
      synchronize: true
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: scs-tenant-rolebinding
      namespace: "{{request.object.metadata.name}}"
      data:
        metadata:
          name: scs-tenant-rolebinding
          namespace: "{{request.object.metadata.name}}"
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: scs-tenant-clusterrole
        subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: "oidcSovereignCloudStack:moin-cluster-all-playgrounds"
  - generate:
      apiVersion: clusterstack.x-k8s.io/v1alpha1
      data:
        metadata:
          name: scs-cluster-stack
          namespace: '{{request.object.metadata.name}}'
        spec:
          autoSubscribe: false
          channel: stable
          kubernetesVersion: "1.27"
          name: scs
          noProvider: true
          provider: openstack
          versions:
          - v4
      kind: ClusterStack
      name: scs-cluster-stack
      namespace: '{{request.object.metadata.name}}'
      synchronize: true
    match:
      any:
      - resources:
          kinds:
          - Namespace
          names:
          - kaas-playground*
    name: generate-clusterstack-playgrounds
    skipBackgroundRequests: true
  validationFailureAction: Audit
