---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-cs-for-each-tenant
  annotations:
    policies.kyverno.io/title: Generate SCS tenant resources
spec:
  rules:
  - name: generate-clusterstack
    match:
      any:
      - resources:
          kinds:
          - Namespace
          names: 
            - "*tenant*"
    generate:
      synchronize: true
      apiVersion: clusterstack.x-k8s.io/v1alpha1
      kind: ClusterStack
      name: scs-cluster-stack
      namespace: "{{request.object.metadata.name}}"
      data:
        metadata:
          name: scs-cluster-stack
          namespace: "{{request.object.metadata.name}}"
        spec:
          noProvider: true
          provider: openstack
          name: scs
          kubernetesVersion: "1.27"
          channel: stable
          autoSubscribe: false
          versions:
            - v4
  - name: generate-rolebinding
    match:
      any: 
      - resources:
          kinds:
          - Namespace
          names: 
            - "*tenant*"
    generate:
      synchronize: true
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: scs-tenant-rolebinding
      namespace: "{{request.object.metadata.name}}"
      data:
        metadata:
          name: scs-tenant-rolebinding
          namespace: "{{request.object.metadata.name}}"
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: scs-tenant-clusterrole
        subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: scs-allow-playground-access