---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: openstack-csp-helper
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    tag: v0.6.0
  url: https://github.com/SovereignCloudStack/openstack-csp-helper.git
