apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: playground1-tenant-access
  namespace: kaas-playground1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scs-tenant-clusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidcSovereignCloudStack:moin-cluster-playground1
