---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-list-clusterclass
rules:
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - "clusterclasses"
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: public-read-list-clusterclass
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: get-list-clusterclass
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:anonymous
