apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scs-tenant-clusterrole
rules:
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - "*"
  verbs:
  - get
  - create
  - update
  - delete
  - watch
  - list 
  - patch
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - get
  - create
  - update
  - delete
  - watch
  - list 
  - patch
- apiGroups:
  - clusterstack.x-k8s.io
  resources:
  - "*"
  verbs:
  - get
  - create
  - update
  - delete
  - watch
  - list 
  - patch
- apiGroups:
  - infrastructure.clusterstack.x-k8s.io
  resources:
  - "*"
  verbs:
  - get
  - create
  - update
  - delete
  - watch
  - list 
  - patch