---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  releaseName: external-dns
  persistentClient: false # hopefully this mimics --wait
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      version: 1.14.4
      sourceRef:
        kind: HelmRepository
        name: external-dns
  install:
    createNamespace: true
    remediation:
      retries: -1
  valuesFrom:
  - kind: Secret
    name: secret-values
  interval: 3m0s
  targetNamespace: external-dns
