---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  releaseName: external-dns
  persistentClient: false # hopefully this mimics --wait
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      version: 1.14.4
      sourceRef:
        kind: HelmRepository
        name: external-dns
  install:
    createNamespace: true
    remediation:
      retries: -1
  values:
    env:
      - name: OS_AUTH_URL
        valueFrom:
          secretKeyRef:
            key: OS_AUTH_URL
            name: external-dns
      - name: OS_REGION_NAME
        valueFrom:
          secretKeyRef:
            key: OS_REGION_NAME
            name: external-dns
      - name: OS_APPLICATION_CREDENTIAL_ID
        valueFrom:
          secretKeyRef:
            key: OS_APPLICATION_CREDENTIAL_ID
            name: external-dns
      - name: OS_APPLICATION_CREDENTIAL_SECRET
        valueFrom:
          secretKeyRef:
            key: OS_APPLICATION_CREDENTIAL_SECRET
            name: external-dns
    policy: sync
    provider:
      name: designate
    sources:
      - service
      - ingress
    txtOwnerId: moin-cluster
    txtPrefix: moin
    txtSuffix: null
  interval: 3m0s
  targetNamespace: external-dns
