env:
  - name: OS_AUTH_URL
    valueFrom:
      secretKeyRef:
        key: OS_AUTH_URL
        name: external-dns
  - name: OS_REGION_NAME
    valueFrom:
      secretKeyRef:
        key: OS_REGION_NAME
        name: external-dns
  - name: OS_APPLICATION_CREDENTIAL_ID
    valueFrom:
      secretKeyRef:
        key: OS_APPLICATION_CREDENTIAL_ID
        name: external-dns
  - name: OS_APPLICATION_CREDENTIAL_SECRET
    valueFrom:
      secretKeyRef:
        key: OS_APPLICATION_CREDENTIAL_SECRET
        name: external-dns
policy: sync
provider:
  name: designate
sources:
  - service
  - ingress
txtOwnerId: moin-cluster
txtPrefix: moin
txtSuffix: null
