---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 1m0s
  url: helm repo add kyverno https://kyverno.github.io/kyverno/
