---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  persistentClient: false # hopefully this mimics --wait
  chart:
    spec:
      chart: kyverno
      reconcileStrategy: ChartVersion
      version: v1.12.1
      sourceRef:
        kind: HelmRepository
        name: kyverno
  install:
    createNamespace: true
    remediation:
      retries: -1
  interval: 3m0s
  targetNamespace: kyverno
