---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: capi-system
spec:
  manager:
    featureGates:
      ClusterResourceSet: true
      ClusterTopology: true
      MachinePool: true
      MachineSetPreflightChecks: false
      RuntimeSDK: true
    verbosity: 1
  version: v1.8.3
