---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kamaji-control-plane-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: kamaji 
  namespace: capi-kamaji-control-plane-system
spec:
  version: v0.10.0
