---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: dex
  namespace: flux-system
spec:
  releaseName: dex
  persistentClient: false # hopefully this mimics --wait
  chart:
    spec:
      chart: dex
      reconcileStrategy: ChartVersion
      version: 0.19.1
      sourceRef:
        kind: HelmRepository
        name: dex
  install:
    createNamespace: true
    remediation:
      retries: -1
  valuesFrom:
    - kind: Secret
      name: dex-secret-values
  interval: 3m0s
  targetNamespace: dex
