apiVersion: v1
data:
  secret-values.yaml: ENC[AES256_GCM,data:xmJIw5aJACIfawOiheLM5qdnXUmDuw2N2R66m9WaGVYC7oavsbogs+kSmkY64ETUkPXNQAhX9uVRYdonIi+H4XSF6f6EuBCjocEgb+aAz3dIvURXQcAdjgN7r+hO7qWcSjcAsRq7so6FZcvs5L85F3Y8P4rChcGRVyMxYvQND2Fpm1OVG10Xx+QNraqhYt+YOMLkfk0/nReTo3V6Lw6gJPxfCJcI6PmbJdwDpDGUWPO1/rFl2FvAjtmBi8WZsXZywDbE6tBfMc1hdopZlaT+pPXWJ7MqiHVndpVPHbRVCCNbpnx81Fz+wj95YHfvONvDi456G+8kYH18qVOwtBBX75W3I5NlDmTDm3146ptlO5e0ur3Cjk+Mqi+Fx9YVkgX5GJJYVlCIR8aeGgR5EE9+PdJgJ8sqXoDxM4QzwBRJ1wFb33zOmGojsI06aZXpUwGGqI293M/zVo6mWsNK7u4AVR4KZBSdoqs3Rh/Zrs+cUgdgkm+RXXeDELA9j3difOpq4hEti0311Kw3hgwE7kXdWXKzCuMuCyqgI4+zpNrIHQj2yJ+VT8xRURvwsSkf8AR5IV2lEdvEIUidE9YkXzkGQQ8rrdh93crtWdtHtIm9jB3+0h/OHYIjg+VOR8R7puN0heKRNSt8G5k2HLnQRF08R8Dj9oqyEMVaBIsdgx4ccVebLUUPmZUrBhfsvPO38zjvZApERZAb40ENKNAOjSegbvDm7OaJ9DL6ZyeDq+jI3v5H71CFdQztGBNw+iVjk+QYueX/9cG45cBS7+ZVtbMFs04BRVo8oP2owDhqkuxIlflkEcpN6Y9SvJ9evWjwFAsgrM1otI7RkvBS/gQZTl9QzJv1c2huBQokqi3dcO5HGVaniIyCKC9XGGCq7v5usjR2V8lnd3y1EfRpItICQG64Rh59mB65sSwHk2oXO6tnrGmdxEfa01yJ5X4IYwa4VBw1YoOo2b5710zJuJryqenWdEcgARTOUD86l4BzwQZQgT/fFivAV+QcOMZJsY7EWZx/0cUmbUDt3dI4d/Qw3a/j6+a9mqduz2Ry9fPv5RKkJMQ/Dl3v3Pt1Uf7yNoZ9AbSz5mETmBYDG3+9zP7tT+uRTYSNbOXfxGaVXxCUFScLvvimdqYzJAwtXOwB86QJ7rx3mc0Is+gm2cQNLP5/pZo0AVtZT9cW1zXkLTDXXLNq0aASXkZBVxBbo4lfYm324U8tx7LJm8gBxcEVQz4abeOJKGK6Y4yCm7vAnUv8e7eP08zxQtAbknxU7+wHQ1HKwH3lbT4bfshRgWUZw23MHvqEhBFudfdQ1/OV6ORC13Q+3mUMJsPsSJk55oDa8wfRCnX1AV1UGaiZ6GYKB+vkqvqeYjOgzgVKUno/mL732Q2waMy1y34GIK/VIjMXGy7Sd+nppiLdIKJvicD+yzoLtrCr0WzshXHIfwoshmdU52PTqbT1XCR1jWLLYuG8CzbTy0X6ZISPGeK+QpjM1ftNEyKZCvmsCQ68yTSykh3asgPzS5oEGgLH0+mM7AM2dEX2rTf5E39eFKCFoDNnmdSYPIw8cl9+yPleaFRE6G9h/WHIGXcVxjonRTlUrM3iRUe68aKQv7RPz79s6kgDqz5D+BfOpt0XSdDgY88Fcv1H4inTWXlltehSiuZDWRdveD1WJTAiGQtzwJhpyoQQD4Vs6BSa8M/ZiN1pyV+2TBwn9k3o0jD3dYFuvRQWqAyukBs75m9FFKAZvJgQVteqwUG5R7i6TwzDBrviaPlgZuUnjMQlP478h6wl+QTH+YFrjuYVCtqXvKGNyJunj5wenyNENdfMLtNgWraVSKzJRMY1I8WTvNtlEXT8OA2DrQD+TXY6oxFuCE+84zs6NEt5lMySt6L1WQPNFFBVX50zMGWAqC3PQN8nHr2jaFmauMcIj4CnA9RsNh0iZOyCQ4/GeCt7O/tECpw/WFzXZwKgXXvpnP9g1yqxgZdp+RxYIEOWo088fpA09wtugQgxb55AFhFyMlsmIGyOaVOaryJ3IqGUhv+p28BjqDO1CZ2JsdUVo0m791OzqcB9SpQKZNIFEyeS8RgkbZJOWiMtty8CvurWdWexoBy1Q/t/7u4zZKYP6bXnzpaN+cINZ/WsNj2JJTK4qmlYiLen4IJU9HGXtMYiLIYvktH9apuNnKkpvfLAOBu73oo7hkSHnGqhSTB+UWzB3Q7v9BzVqOi/lYs7+uX0Z15x8xYPRMBtQTcHD1eKUMN0c6UXN7+/e19nGjLIHb+cl2eMmDz+M6/Cepg1YNtF8g9o8Pv/JHgpLcGU6yvcRF/qa6FObIz0hUcvuYLSMuOUA7vpLcBOSLxPkcsDCiYadTDwMSvY1eu7VZkJHI2crlUn+KyD4mL1uuiWraTQX1imSTcz+GRccVOYVNa7gdXiMy7UrThAuFDVsZQIaJ9iOnwNnCeVjFsNQhC7TPP+/jFJaxyfoP92LdNJecKEsmp8txW8ucIp/qK9WKPSZcjto567nmEcZVZiuM6v2CL9rGxGUiR/NXeWkClLxXp/VH3P3bQ/BolChQcPCA+WdL9nc6HWIEJNC7bAp77iuD85pswqszHNlH74h3URNz6cprUyp5cAm0w+Lh5udKLqa1bmUQ0E8anH+ulzWl0wbufNxULVf3ZsyaKu5Ab2xjUlDUGvXU92YgzAY+KSqZTqndRp2Oqs7eQOp9u9iEJAgjH600Np7Ke62dOiIdc7PB4pa8UYyFTtw+/f/OuzcunrelQ9sHqQ4uTfYJiRrlvDFcB+XziEKM4yAMcS/kZvgROKDiG4h/zu6sPYQFfUWLYnB8SJWFBhgsqwx+ie3I5Hy9TDKYB251mqan4TmiOOX6aH3APEb5zwukNfihBiJIuPu6SC1ehPcLemdkAjR7MtSpVXdKIeFoRZbYniXKZjuioK28LNTspbDNLEiRdA,iv:fr6N9ZiUTwksb/KhvVAb3mSw8wfq1ILOq85hpoqmvis=,tag:MI2zbqnckNlVdBb1y3jvpw==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: dex-secret-values
  namespace: dex
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2024-10-15T18:44:24Z"
  mac: ENC[AES256_GCM,data:6nyqqcvsjSjbGph4FjmUBX/RdwyIGAtcAzI/tGiCAJEx5uGhuCtRYqF0MKZQmDTCnXKYLht5xft8PqstofdhglariNdP3x9rPzX3olfXrlIWccZvNOSFx6rGrgo2gKQax59tpsSX6BBK8kH5KvKE6JhE96tUJMcNWCxjkiTMII4=,iv:4ugomLGR+Vs2eACVr1mYlon7ibmcIoSTeZcvqtMkRAA=,tag:zp77zt9Z+uu+4I0UgI20FA==,type:str]
  pgp:
    - created_at: "2024-10-15T18:44:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        wcFMAyBxDD99NeTXAQ/+OcjD6xwxOXkW5o2FccP/bO6lEv0ZLbmfzgAAqFkatqIZ
        ojIetCv2VUpFGJe5lfgKwWfAgr/NR+sKueOZD0Oxe4XMy5mKUov7mFQ56ceyaKOm
        +0oTgtyiGsP9ytRwwPjQoLHZ56FSSMsKtCh22N/ZI0AVd625weZbLM22z78t+qds
        HSffsovrw2UlIjZJsy64lvyy1lJdLkUa9ZgkVLfykln7B9erQGsalQXdunxV2bgN
        Ue7JMyrtu8mx0agonE2LSQ02Ehh4itOphBlPYuA5gOg8S8KhVbA4SGP/oDTV6bH+
        KK6xBsvCzilP4XDqemJ/Q5cy7zNR9v5Y6VX5oyNABZHejUrNNT/5eaOoXoazJvEE
        tnCJuEY8q5zkLI5lLCfCtnoAxMZ8VdHPG51bJvPhlKRq9jlycfMOgumJQvQ2jghI
        WCJqalZFxHyWTErN3fI0gaeA3XkQl3cwFBZJpHrm+C4ycPr6BTbzGdPXuMsKNLVh
        7jGlLORgrWWCpVFdYF1N9lwhi5p5x/d8fKvXjtgvCIKZizMGxtPlcruvIfA+fGxi
        uYoGGWLjePd7Yhc2R8BxVFdh9n7GOGsy++3m6tDWBakJqbBdbT2spPCbBPX5JDt7
        gnC8sTk1kNO1OGbftCYLaGrTvUsfAmf5kXw78mTcBZ+GtTiM17X5vsRN29bg4SDS
        UQFJTJMmpVMCoD5M+v7S7xl9WCd16MKAeMTJztfrAEluIAN25nbAQgJAuHLDl1Xf
        L5y0Tfhc1tzZMm8pcjYHL7ka6sq+sVSjLDzNLqd4G84RQw==
        =WWVK
        -----END PGP MESSAGE-----
      fp: CCCA3F0D6E841833AC56DAED48E4E0C7613AAB14
    - created_at: "2024-10-15T18:44:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        wcFMA6Kr4c7HLrmXARAAtXoGTwXNhlH48SHFZJVry/y495se/b3lzIc3q0hmTBj1
        LlR+uKiSNlsI+qr6tW2FTqxlq0z6saeiNUaip0pDdB+hzxCMktaO/xtbh3PYSYHS
        UNfJrHMFCdoNJbpFxbJ392gj8aAswC7HVnZsaTwfOZDHlo2bxJNPvjVZAXJyuEr0
        JJaEPzHjuL/QwzHrteH++3qOoV1hBbrJtrQVG5DshaZVNFjshtZPCXux2vrfYNjn
        uAnRyLHmPdg++kYqFdtjp6hciIRUIgfT9AvfCQFdzrYZBBJmCVvECZIvn10zsv8e
        HMmzhG7QNxCBO54I2f94lMEYlsD3wjmy2s+l9mII8ixW3L1O4D5LXCBRHUHyjghm
        mZADdY08EwFBxnlhOUhUKVqH6I4yanzXGEyms86QiO4sMj4taAmqlT8gWg7Fv5Hs
        FA72ery40U0dp+I36uxmlGtSJEk5RAmwv9YlNFhkLE3c/96J5cS0tF2AiZ7oGAzy
        RDnOMF3gUKDo8K8GhyN1sZeEf1EDdlIUMUBGkSar0h5My8WH1K/rzQaOJ4n1NHB6
        MNzPIMgDS9hZXkTFSza06K9qpH3Ug6Z7k9SBTm3I8y49TbT+yZOkkICkMW/775c6
        SNJQhAaUIqDtHjLEc8IGX9OTltZrvmo96EsqMcbPF5DM3G3GkuHBJbvhLXmaP27S
        UQEtCJzljSOdUbKD40yLcWYO1tMKzRZisaKE5VC3Eqof/xOdL8hjEK8GvO+lwXcY
        fY1sQNyoL4DsZP6rkRU37gTtq9504k5KyEq81qp2e1xtVw==
        =XYdW
        -----END PGP MESSAGE-----
      fp: DF71497C07110D584ED5D379CB3A922F8FAE3D50
    - created_at: "2024-10-15T18:44:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        wcFMA/o5Gaf/w6e6AQ//fmwnIzHBenYxtSW4fBOw38r3qICKMYo6EMizvDfL6L84
        Z+8mAlRhFHsDcWSj+ljfKY4csmr0vGiTI2vYJBXlbt3grK2z5ROBp/R87UDlpMOZ
        eLyEZzhstDAPYtFX7wz5uu6H7m6OIdkECGqp4/tnjIRfWTX4K8yM1ha2pdw3dYfZ
        LBtujJ09+fqAvASkh1AhepYL83YZWOf5iq3UxZDkWt2NL2g4LoHhlgOGZHrBzCrd
        MT9Xn50TAJBpaNFmwFFf1NT3c3/pDBhKduJlGVZe7GwJV++LKKHxM+RMN5vnnZ8i
        d8WzRC5GXAw/EBcl50xbY7XXwdWYCVJPnw2+sK3g0RCySgs3Wa/V19h71Q3ucvoK
        vfWxV81G7FkcAWhmI8kihfwiQ4ZVkYxjnpga86QB8kwX+yFECXr/0quDeU4IPDc6
        Y13X/LT6rXhfc+wbMyalIv/EyShPjINCcEm3zHG08id4Rvu97KVcj4Pl+OjrTkFx
        QRWe3soCzMaHlM6CbCz3DS+U0w/AqAB4dit5WvNsDK35F8iYUMnbcBzN53v0oBgq
        gHZBEbJBku09m1k9NmO2it2AJg6tBHppxQPknFG4VX3rgLzjPd2RIcbVz5OANYZ/
        fh6Nvlg2s9kgG745wBMA/bQczKPoU5Py6C8SQgLvKohodMrxmtOf/wCPdtPHnQnS
        UQFNxkwk8tlSw6OL73R15uRHT4PI6NnE0oKIsyO5o99+ZSG8LC3frCrlMVRVHc1h
        9jFsIL3SHCrt+IKNhUTCtEAyGPHNvzbxbbkLoy/QfOeSEg==
        =phnr
        -----END PGP MESSAGE-----
      fp: 5AAE7807A91FBAA7A5DB246B52A2E96A7268BCCE
    - created_at: "2024-10-15T18:44:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        wV4Ds9lh1tfJlukSAQdAt0AhswE7hoQffe24kD9PUQQvy2Rv6k08YDcM/LTaYEsw
        fGkJO6KuCpLAlkbmfEiwbJ9AMr7Ety24M8n8/EIQaopF9x3rlGZr3F3d9BjTK9+Q
        0lEBx4/e/JUXHcXBkIIoMGwgod87PUKu5k1G1pebJYzQfsy8SV31GWIQ1mR0tW8t
        21DWqBUUeCAuOzFhE/ubX+AsUxyifwDBygIbO14m824Qr6Y=
        =2U9N
        -----END PGP MESSAGE-----
      fp: 6A413E28286599A84595529EB2F65CBDF1C65D3A
    - created_at: "2024-10-15T18:44:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        wcFMA2VTGvlVjirjAQ//VErdxDqWQga7Y4WSilVW94mytI/xubThf9bF2hLeH49A
        RjWTsQO5UlmUZkhJ1f8OfQHkz4oZ8fUw/S5+3iQ2L8/RZO0BMzV6p8nYdPi88nk8
        XDsCBcWPH5eAqm06eVV4fq27pl2b8iIysAxn7HKwD4aEOyiU/fPQKW45tq3KedIl
        QQY+sNdTQTpUCym2KOzqBfDGVesjS8L7mkPuK6UmrQVYD008GtahVIEah7Y/LbWE
        vDhBx+bjAu0gA9jwIFEb/xNfSTjwBcTHyN+VbVDW3NOWDPBEn12gOpqHBxsXRYem
        KP7rpWoyDJXU/0SV7ls53U4yALaji18ekugxuaj5lkRJjqRw8WW0DMQNefdau9WC
        8j6ThPMaL0d+oDh2wWKVGChAHeD4ElfPJIVKbW6rljcjS3KYxK/B2bgHQAgnMerp
        aRTZPoOp4tCwCOnGJFH8mQ5vnqjRPCUM395AsVBZiA6lEdiEbxwqoAeAIs+GrkSn
        k7dplXidGhh8JQypcvgxuYdAAGeb5TMdkGFmRVRr9obMH0+Xy6woYVdSd3R1+rLa
        cp612sVdUctuZa+JXRGPNXgwb8D350+q2AzE6nmPoIee37fT2MOeGeNuGCnFRIHy
        uEU6lVYj5AbzbKTRdU/tGWzCWXKWDHjx7zcvLFjvQjy+TgbMdgvfSfyXlOvsFXHS
        UQG2J3caJbwA6D1KMkm8ato2BsofX5e4hJhQOjUfL5cgL8UcGkArygE2GQhO4FDk
        XIS3kgDNAZ4vhNk8x3xiEr2HNjNTuqofmCqznEm9h6uPAw==
        =cJPb
        -----END PGP MESSAGE-----
      fp: D48108A56B0EB04A40DEE96775676F49EAFAA9CA
    - created_at: "2024-10-15T18:44:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        wcBMA/CESpP6bvPkAQf/Zla3BAvjC9WBaQqccTI2UgTQPZmM8teme+CN1YKGNc/T
        x2h+XZcSZeuFj/YZ30CfphT+PvXgTm7XtZ5Vtc1G4QMXOGYuLJVlWfRgKF1J6NmH
        wypZFKdsZRZV3M5bM1g0PQyxBCih1hVhw45VR4q36fB4NsPuVHzafBqbxaB4JzYu
        OX9uJf0PdcWYPRnOdKIxGhSx2j/wl52ViagJAgtj2iVxn+WBjQVXYepykFkG5c25
        0i63r1RZOV/8AKu/QP+0jXUpQBsLXZfebL/kU55Y3yisSQLwow1+PlgDSyJGTEq8
        0kiUAz2hy2DCIRe0eMP++wBeI9BZBkiwJbYjrUgWp9JRARFykKxvYbviP8k5oKqW
        GMEyFM1bzghnVPBPgJ+PWiZN5Qn9msJwBjmyyxGNfyhzW3FAWAZa11/f9JwA4PhC
        VVwWy1jyXcjlxIkfU7rUo2ES
        =av0w
        -----END PGP MESSAGE-----
      fp: B6829414FCD33331EBD08EC3F70112A73CB97C21
    - created_at: "2024-10-15T18:44:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        wV4DbYZvvToLQQASAQdAjBzmwjB+B4FWc5AGSs19bsdf7bOGCTpdX/IG4d2+Xx0w
        V7asuyE7EIlDiXnOwkRi6+C+XnLBS9HRwvsh+cUbdqgga9l5cLiaTg1IcJLoq4CY
        0lEBQbHqnlIcJINLVatSyisGt6p3MoF+JJ9xMY2EhAgMR7uUv4gMVC0D2ojNUS64
        V3C/TBVb34puSrtoiiNAvSQBavrWNrtITIaGOd9T/e6pvYk=
        =K2Xj
        -----END PGP MESSAGE-----
      fp: 92842ACE52D2B8C77F9A59662AAB6EE5E2C8EE71
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
