apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:d5FB3ZrsVQLJP1jJZ/lf1T5AibYORiktbapyUeDGO/tvvuHV9IVDA+vHpUqolHDVbP3Xd3315OJcqxYOXLyO6wQ3njCQb4q6xpDe4K0N0NJq5y2XmailLZmSLi5a9yMQm902khX3Dgfce6jWU5C08kLBWAAk1xzLl1NH9/kzRFQ2KN0PD0IdLmQTbGI9yVaceGEwEf1md9DCH+eZJjU+vzAmawvy9s2TwrvjX2u2r3Fn6IFUcUrzaPMIq/9zNC3LGqRJTl9fgIw23jBaywk88maAcNTSn7zmJ+/rjpSzsPx53tXrLzeVEohYQhUmLQs+ETaLikz9JVHhhHq1ZGrEi66ff8GJkg8+YWouhwkmjYx89O2ITQQ7KgYllREuaen1uXH0G+FR44cbEz0OTpcIuEC89065HWPUGhpF8NqsUG+B/CBTa4rw6E6mmcOPgKRwFhdJPSDushf6Tu2RHhzpy3q0C2vRZob5KFKdWPcX2xkNC54oB4kFm8+ob2LP4HOy+APvZaj3Yxg3SLfln67DHPBzihBHlo1Hmo1RflZwblyJ0U2IpcWjS2Sh/gTCfkD7WycDhKikvNsu4ZozBE4fjlI+irR8ypKLdtUJWiQ/Mm2WkX52fVLVGGwRn26EYmdNsimsYo58QIP59v1ecGp5nMQKhDqE4inROPOVhT+ZC7KR2CLOpCLTK85FkhlaafMWQ5cPU7IYCrUi9vm/JG4P6UGQV+okpbF/yC56yZs8nCnr6bDGOa8pWMZqR9982hfRs0CKRDnWeY7SfdIIzilgRxyiHEopSQJP7M0rH2Jg5LAsP+Dmze/RyhySHY4EfxjOg3H5zD3x8Q2QykgrJ9Lw+1FIfZMeZl44nEQxzmnj8s4qzEzMC4K5ppeLDWB20fiTgS39/E7IV4az5RVf8MAXFv0kZlyZEIwbRx3TKerl/tu1Kbf7PvLi0CK7ys4diz9GkN2seoS/hn41AWXOVNlCHwc6YNLF3dKvYJUIaav3Z4KywHT1XoAmViX+Yl9Mc71Gb2n3Tfr3PM8tIem7rzI3quCPofjlnck+cVGMX0yo3NxaqymSFgBQjkuLTDCmIq+Ehmim45ZN6LhOFepMASwbyabpeIkdQd9M4+jsZ22ATCBPNbAScCZvQpNqm//rZreGUA0vqX+/47IENP+DXWAhEJyzgSS0kF/god/hVPnkHHEP+NvLSIoZdPKWO8CIKcyXtZD/ZQ5pwTF9YrerKY6OMzQkTVNslI6Ezo3ZsYe4EiqydJr73y5kqCbmlU/yDYQYtWi/X8n0t6nGwfr6eK3En6TUOi4HmKfimQIgfAPBnvCmlElx3Z9wESM69odIVu4WjFbX3YmbmYSt/LnrARO6zMziu2VqNDkZ8fiFWV0m+bJqD1uMYkIBau0lkMSWDHIuzATBKRxtoSl6OzVXjvKA++0GuHo/tf3uxU3TaSKhtuN4kSFFuirUUevXHliumTdergif8G/q+5sD07crVE2UIaYZ0t7GpUDNec/qDISgzlAblwx+l3rcw74ZOQaHZEUPjzzRrgRJuLnqw34NdzsE6zftkBfOV8eTDw2TKxSkGgzYTxOd5vHx72t9VT+DvBfNqT0L+cyfJLMEnUSD72K9F5nIVe4XffCGFHm7W2rnP/167u8MJi8oXbKqPmzP25r4VWRbDnOoilb+h5WAqktlB1BGArdx2OPnaCydFIdzyy7Rbmnth8SZY3EnyDbDRRieOlwU3zHwEqcwpNmNq7AGMtwYfCXFFxbkq7G22+PCsoNjZs6FgfgzsmmoQeo6RwXGnqSf/CpRdDhjRZyQIzgKjHJisxIX93AV6GlHlzd23MLn7IkgVqct5UqaXNZd5hwWbQK+PgOudUwqhCKwGENxtiHt97KHfzUnJSHNXJ+9uFCD1qp0jsYGRxIlmBPQuuwYUo6umPoD5hnOgsB47J7p9CFeqAXfdYzRlbS8v7KWFM/05w5eN3MTNVfP7glnHUCAjAmRzFhQ2e11PZwaqm3f5+lCuYIW3SLPayaEw+XMp6lXto2ZUrC8PZDpf1KBjtLNhnewcD1uGRTOoGsvG8C6z4D8JAlm0PY0aNJLFCn54+msrkpuVRSrp3cAs7/7N+vL3a9d3Bds16mAbJlEGcsTzPmroybGC76pvUIg+ZIZmPxQI1ccO+4pNp1Gs6WAhOHifQd2j33yn29LDhiLGfPEk/x8+Vg94QglCKqysNu9IEmOHOgMAr1ehimP9fYHm2O3zW8lK0vsqvgU3fxDqeIkxdjBIHFFg274lOxVAQ/dEoZQPKLIpya1fZ4u9LM7VGEdSw+l42gyQm4CLvolY2btvRn+I+5Lx/tJjaX2rEqqfsMbZm6wtbrB4+/Mwl5gbuF76PAlz6hBdPTjuwvT2BEMAtZNqv88iwthOKy/rGlAFi5h60xtMvjNnYXWAw5LPVwhRbCOCk1fbL3TFH3fJCEEscQNRAXK255GgQodMBWNoWznkIYDRHFr1q70xHBXmbgkNwc3p/8FLTeOlMyeBqQVwWNMSLtBWyvXlZzs4LBq7Fc2OZKbytcCgMPJHV4kxXRoLnIIgrTkwova+G+wsRUdOv0KfIkAoPwg4OQu4bpXXNBE/UatM2uF4f8JuZxHWs9TYQ0wNxKsAGuJU1OqdjmHO0pKMKdHSfa56A9tj6zZqRpedASDpyfBPUm+t0QtgknIlo55pEIK+oGFPO8zFOWBrb4A1aLn7v1/3X/dRYk4KofJlhXpcHuktZNhOi35Z2H4JEQtGkUB3K7wx6rhoUQ+JRIWI5J/YXq6K518SUtDJNP1AMOF+YlC2u0K2wMt5Uxxc3SWzAxIr1PKMlTN+UdmFtvI+4bsPcerpfA28yC28zjFcnXc4Tzr738JFdZo4UAHk/LX/aZLmRtMciQkfqe4SZVOzUy3tyIIMgy0dBqqniYKvmk4,iv:mfJuoyb4myNMVLLgd2VePpLUHSrVi67osVwVopmKRm4=,tag:oMRo+BAWwBhq3muPpHkb2A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: dex-secret-values
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-15T18:55:28Z"
    mac: ENC[AES256_GCM,data:JBz6HWQTh8PyDYM2yah3JT6EOTXVaSy/jiSQSqjmbFHUy04NPrW8172GUjjkNV7LyHOKwjq2RItfMIdiZU5m/W7a8HJwe3v93xQ6x7p9Bz/DnYEuLRGHRW/UUPyd1HB9LZvjDh2PUTXkUFJ6Ejbgg1rDO5226EnemSfkWkmFiuk=,iv:HDe4ix8ZApEu/j8hbqvcJf0NKvXpe/4ee8GIa6O0i1I=,tag:S5P3yjFRCry0GLFTZWgsCA==,type:str]
    pgp:
        - created_at: "2024-10-15T18:44:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMAyBxDD99NeTXAQ/+OcjD6xwxOXkW5o2FccP/bO6lEv0ZLbmfzgAAqFkatqIZ
            ojIetCv2VUpFGJe5lfgKwWfAgr/NR+sKueOZD0Oxe4XMy5mKUov7mFQ56ceyaKOm
            +0oTgtyiGsP9ytRwwPjQoLHZ56FSSMsKtCh22N/ZI0AVd625weZbLM22z78t+qds
            HSffsovrw2UlIjZJsy64lvyy1lJdLkUa9ZgkVLfykln7B9erQGsalQXdunxV2bgN
            Ue7JMyrtu8mx0agonE2LSQ02Ehh4itOphBlPYuA5gOg8S8KhVbA4SGP/oDTV6bH+
            KK6xBsvCzilP4XDqemJ/Q5cy7zNR9v5Y6VX5oyNABZHejUrNNT/5eaOoXoazJvEE
            tnCJuEY8q5zkLI5lLCfCtnoAxMZ8VdHPG51bJvPhlKRq9jlycfMOgumJQvQ2jghI
            WCJqalZFxHyWTErN3fI0gaeA3XkQl3cwFBZJpHrm+C4ycPr6BTbzGdPXuMsKNLVh
            7jGlLORgrWWCpVFdYF1N9lwhi5p5x/d8fKvXjtgvCIKZizMGxtPlcruvIfA+fGxi
            uYoGGWLjePd7Yhc2R8BxVFdh9n7GOGsy++3m6tDWBakJqbBdbT2spPCbBPX5JDt7
            gnC8sTk1kNO1OGbftCYLaGrTvUsfAmf5kXw78mTcBZ+GtTiM17X5vsRN29bg4SDS
            UQFJTJMmpVMCoD5M+v7S7xl9WCd16MKAeMTJztfrAEluIAN25nbAQgJAuHLDl1Xf
            L5y0Tfhc1tzZMm8pcjYHL7ka6sq+sVSjLDzNLqd4G84RQw==
            =WWVK
            -----END PGP MESSAGE-----
          fp: CCCA3F0D6E841833AC56DAED48E4E0C7613AAB14
        - created_at: "2024-10-15T18:44:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6Kr4c7HLrmXARAAtXoGTwXNhlH48SHFZJVry/y495se/b3lzIc3q0hmTBj1
            LlR+uKiSNlsI+qr6tW2FTqxlq0z6saeiNUaip0pDdB+hzxCMktaO/xtbh3PYSYHS
            UNfJrHMFCdoNJbpFxbJ392gj8aAswC7HVnZsaTwfOZDHlo2bxJNPvjVZAXJyuEr0
            JJaEPzHjuL/QwzHrteH++3qOoV1hBbrJtrQVG5DshaZVNFjshtZPCXux2vrfYNjn
            uAnRyLHmPdg++kYqFdtjp6hciIRUIgfT9AvfCQFdzrYZBBJmCVvECZIvn10zsv8e
            HMmzhG7QNxCBO54I2f94lMEYlsD3wjmy2s+l9mII8ixW3L1O4D5LXCBRHUHyjghm
            mZADdY08EwFBxnlhOUhUKVqH6I4yanzXGEyms86QiO4sMj4taAmqlT8gWg7Fv5Hs
            FA72ery40U0dp+I36uxmlGtSJEk5RAmwv9YlNFhkLE3c/96J5cS0tF2AiZ7oGAzy
            RDnOMF3gUKDo8K8GhyN1sZeEf1EDdlIUMUBGkSar0h5My8WH1K/rzQaOJ4n1NHB6
            MNzPIMgDS9hZXkTFSza06K9qpH3Ug6Z7k9SBTm3I8y49TbT+yZOkkICkMW/775c6
            SNJQhAaUIqDtHjLEc8IGX9OTltZrvmo96EsqMcbPF5DM3G3GkuHBJbvhLXmaP27S
            UQEtCJzljSOdUbKD40yLcWYO1tMKzRZisaKE5VC3Eqof/xOdL8hjEK8GvO+lwXcY
            fY1sQNyoL4DsZP6rkRU37gTtq9504k5KyEq81qp2e1xtVw==
            =XYdW
            -----END PGP MESSAGE-----
          fp: DF71497C07110D584ED5D379CB3A922F8FAE3D50
        - created_at: "2024-10-15T18:44:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA/o5Gaf/w6e6AQ//fmwnIzHBenYxtSW4fBOw38r3qICKMYo6EMizvDfL6L84
            Z+8mAlRhFHsDcWSj+ljfKY4csmr0vGiTI2vYJBXlbt3grK2z5ROBp/R87UDlpMOZ
            eLyEZzhstDAPYtFX7wz5uu6H7m6OIdkECGqp4/tnjIRfWTX4K8yM1ha2pdw3dYfZ
            LBtujJ09+fqAvASkh1AhepYL83YZWOf5iq3UxZDkWt2NL2g4LoHhlgOGZHrBzCrd
            MT9Xn50TAJBpaNFmwFFf1NT3c3/pDBhKduJlGVZe7GwJV++LKKHxM+RMN5vnnZ8i
            d8WzRC5GXAw/EBcl50xbY7XXwdWYCVJPnw2+sK3g0RCySgs3Wa/V19h71Q3ucvoK
            vfWxV81G7FkcAWhmI8kihfwiQ4ZVkYxjnpga86QB8kwX+yFECXr/0quDeU4IPDc6
            Y13X/LT6rXhfc+wbMyalIv/EyShPjINCcEm3zHG08id4Rvu97KVcj4Pl+OjrTkFx
            QRWe3soCzMaHlM6CbCz3DS+U0w/AqAB4dit5WvNsDK35F8iYUMnbcBzN53v0oBgq
            gHZBEbJBku09m1k9NmO2it2AJg6tBHppxQPknFG4VX3rgLzjPd2RIcbVz5OANYZ/
            fh6Nvlg2s9kgG745wBMA/bQczKPoU5Py6C8SQgLvKohodMrxmtOf/wCPdtPHnQnS
            UQFNxkwk8tlSw6OL73R15uRHT4PI6NnE0oKIsyO5o99+ZSG8LC3frCrlMVRVHc1h
            9jFsIL3SHCrt+IKNhUTCtEAyGPHNvzbxbbkLoy/QfOeSEg==
            =phnr
            -----END PGP MESSAGE-----
          fp: 5AAE7807A91FBAA7A5DB246B52A2E96A7268BCCE
        - created_at: "2024-10-15T18:44:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4Ds9lh1tfJlukSAQdAt0AhswE7hoQffe24kD9PUQQvy2Rv6k08YDcM/LTaYEsw
            fGkJO6KuCpLAlkbmfEiwbJ9AMr7Ety24M8n8/EIQaopF9x3rlGZr3F3d9BjTK9+Q
            0lEBx4/e/JUXHcXBkIIoMGwgod87PUKu5k1G1pebJYzQfsy8SV31GWIQ1mR0tW8t
            21DWqBUUeCAuOzFhE/ubX+AsUxyifwDBygIbO14m824Qr6Y=
            =2U9N
            -----END PGP MESSAGE-----
          fp: 6A413E28286599A84595529EB2F65CBDF1C65D3A
        - created_at: "2024-10-15T18:44:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA2VTGvlVjirjAQ//VErdxDqWQga7Y4WSilVW94mytI/xubThf9bF2hLeH49A
            RjWTsQO5UlmUZkhJ1f8OfQHkz4oZ8fUw/S5+3iQ2L8/RZO0BMzV6p8nYdPi88nk8
            XDsCBcWPH5eAqm06eVV4fq27pl2b8iIysAxn7HKwD4aEOyiU/fPQKW45tq3KedIl
            QQY+sNdTQTpUCym2KOzqBfDGVesjS8L7mkPuK6UmrQVYD008GtahVIEah7Y/LbWE
            vDhBx+bjAu0gA9jwIFEb/xNfSTjwBcTHyN+VbVDW3NOWDPBEn12gOpqHBxsXRYem
            KP7rpWoyDJXU/0SV7ls53U4yALaji18ekugxuaj5lkRJjqRw8WW0DMQNefdau9WC
            8j6ThPMaL0d+oDh2wWKVGChAHeD4ElfPJIVKbW6rljcjS3KYxK/B2bgHQAgnMerp
            aRTZPoOp4tCwCOnGJFH8mQ5vnqjRPCUM395AsVBZiA6lEdiEbxwqoAeAIs+GrkSn
            k7dplXidGhh8JQypcvgxuYdAAGeb5TMdkGFmRVRr9obMH0+Xy6woYVdSd3R1+rLa
            cp612sVdUctuZa+JXRGPNXgwb8D350+q2AzE6nmPoIee37fT2MOeGeNuGCnFRIHy
            uEU6lVYj5AbzbKTRdU/tGWzCWXKWDHjx7zcvLFjvQjy+TgbMdgvfSfyXlOvsFXHS
            UQG2J3caJbwA6D1KMkm8ato2BsofX5e4hJhQOjUfL5cgL8UcGkArygE2GQhO4FDk
            XIS3kgDNAZ4vhNk8x3xiEr2HNjNTuqofmCqznEm9h6uPAw==
            =cJPb
            -----END PGP MESSAGE-----
          fp: D48108A56B0EB04A40DEE96775676F49EAFAA9CA
        - created_at: "2024-10-15T18:44:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA/CESpP6bvPkAQf/Zla3BAvjC9WBaQqccTI2UgTQPZmM8teme+CN1YKGNc/T
            x2h+XZcSZeuFj/YZ30CfphT+PvXgTm7XtZ5Vtc1G4QMXOGYuLJVlWfRgKF1J6NmH
            wypZFKdsZRZV3M5bM1g0PQyxBCih1hVhw45VR4q36fB4NsPuVHzafBqbxaB4JzYu
            OX9uJf0PdcWYPRnOdKIxGhSx2j/wl52ViagJAgtj2iVxn+WBjQVXYepykFkG5c25
            0i63r1RZOV/8AKu/QP+0jXUpQBsLXZfebL/kU55Y3yisSQLwow1+PlgDSyJGTEq8
            0kiUAz2hy2DCIRe0eMP++wBeI9BZBkiwJbYjrUgWp9JRARFykKxvYbviP8k5oKqW
            GMEyFM1bzghnVPBPgJ+PWiZN5Qn9msJwBjmyyxGNfyhzW3FAWAZa11/f9JwA4PhC
            VVwWy1jyXcjlxIkfU7rUo2ES
            =av0w
            -----END PGP MESSAGE-----
          fp: B6829414FCD33331EBD08EC3F70112A73CB97C21
        - created_at: "2024-10-15T18:44:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DbYZvvToLQQASAQdAjBzmwjB+B4FWc5AGSs19bsdf7bOGCTpdX/IG4d2+Xx0w
            V7asuyE7EIlDiXnOwkRi6+C+XnLBS9HRwvsh+cUbdqgga9l5cLiaTg1IcJLoq4CY
            0lEBQbHqnlIcJINLVatSyisGt6p3MoF+JJ9xMY2EhAgMR7uUv4gMVC0D2ojNUS64
            V3C/TBVb34puSrtoiiNAvSQBavrWNrtITIaGOd9T/e6pvYk=
            =K2Xj
            -----END PGP MESSAGE-----
          fp: 92842ACE52D2B8C77F9A59662AAB6EE5E2C8EE71
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
