---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-visualizer
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/capi-visualizer
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
