---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csp-helper
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/csp-helper
  prune: true
  dependsOn:
    - name: capi
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
