---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  dependsOn:
    - name: cso
    - name: capi
    - name: kyverno
  interval: 10m0s
  path: ./flux/kyverno-policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
