---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: scs-cluster-class
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/scs-cluster-class
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
